site_name: Asynchronet
site_description: Asynchronet - interact with network device CLIs asynchronously.
repo_url: https://github.com/huntabyte/asynchronet
repo_name: huntabyte/asynchronet
theme:
  name: material
  palette:
    primary: green
    accent: orange
  icon:
    repo: fontawesome/brands/github-alt
    logo: fontawesome/solid/ethernet
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
plugins:
  - search
  - section-index
  - mkdocstrings:
      watch:
        - asynchronet
  - termynal
  - autorefs

nav:
  - Getting Started:
    - Installation: index.md
    - Quick Start: quick-start.md
  - Code Reference: reference.md

markdown_extensions:
- toc:
    permalink: true
- admonition
- attr_list
- md_in_html
- pymdownx.highlight:
    use_pygments: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.betterem:
      smart_enable: all
- pymdownx.critic
- pymdownx.details
- pymdownx.highlight:
    linenums_style: pymdownx-inline
watch:
  - asynchronet